CREATE TYPE status_types AS ENUM (
  'started', 
  'in-progress', 
  'completed', 
  'deleted'
);

CREATE TABLE characters (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL, 
  major_trait TEXT NOT NULL,
  created TIMESTAMPTZ NOT NULL DEFAULT now(),
  modified TIMESTAMPTZ DEFAULT now(),
  status status_types NOT NULL,
  user_id INTEGER NOT NULL REFERENCES character_creater_users(id) ON DELETE SET NULL
);